title: Norwegian Environmental Sector
description: Norway's environmental sector through a diverse range of domains focused on conservation, research, monitoring, and sustainable management of natural resources.
uuid: 4eca8d1c-0f3d-4177-92f8-e1c860dc6503
domains:
    - adgang.miljodir.no
    - artsdatabanken.no
    - artsobservasjoner.no
    - avfallsdeklarering.no
    - biodiversity.no
    - cites.no
    - climate-cryosphere.org
    - dirnat.no
    - elvedelta.miljodirektoratet.no
    - elvedelta.no
    - environment.no
    - environmentagency.no
    - erdetfarlig.no
    - fiskeravgift.miljodirektoratet.no
    - forurensning.no
    - grunnforurensning.miljodirektoratet.no
    - hannashus.no
    - havforum.no
    - havkart.no
    - hjorteviltregisteret.no
    - jegerproveeksamen.no
    - jira.miljodirektoratet.no
    - kart.barentswatch.no
    - karteksport.miljodirektoratet.no
    - kartkatalog.miljodirektoratet.no
    - klimatall.no
    - kulturminnesok.no
    - lakseregisteret.no
    - luftkvalitet.miljodirektoratet.no
    - luftkvalitetinorge.no
    - miljoatlas.miljodirektoratet.no
    - miljodir.no
    - miljodirektoratet.no
    - miljodirvideo.no
    - miljoklagenemnda.no
    - miljomal.no
    - miljoprovebanken.no
    - miljostatus.no
    - miljovedtak.no
    - mosj.no
    - nansenamundsen.no
    - nasjonalparkstyre.no
    - natstat.miljodirektoratet.no
    - nin-felles.miljodirektoratet.no
    - nin-prosjektinnmelding.miljodirektoratet.no
    - ninapp.miljodirektoratet.no
    - norgesnasjonalparker.no
    - norskeutslipp.no
    - npolar.no
    - nyalesundresearch.no
    - polarhistorie.no
    - produsentansvar.miljodirektoratet.no
    - produsentansvar.no
    - prosjektrom.miljodirektoratet.no
    - ra.no
    - riksantikvaren.no
    - rovbase.no
    - rovbase.se
    - rovbase30.miljodirektoratet.no
    - soknadssenter.miljodirektoratet.no
    - tilbudsportal.miljodirektoratet.no
    - trondheimconference.org
    - vannmiljo.miljodirektoratet.no
    - vannmiljofaktaark.miljodirektoratet.no
    - vannmiljoklassifiseringtest.miljodirektoratet.no
    - vannmiljokoder.miljodirektoratet.no
    - vannportalen.no
    - wiki.miljodir.no
